### ISSUE TITLE
Error Compiling the Solution

### ISSUE THREAD

**Issue by HotMoogle** [jm33-m0/kms-activate#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to find manifest signing certificate in the certificate store.	win10-activate			

and 

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.	win10-activate

**Comment by jm33-m0** [comment]
You can just use the precompiled binary, or follow the instructions the error report provides
