### ISSUE TITLE
visio

### ISSUE THREAD

**Issue by NoverNobida** [jm33-m0/kms-activate#6]
是否支持visio的激活？能否添加零售版到批量版的转换？

**Comment by jm33-m0** [comment]
据我所知，Office是没有零售到批量的转换的。至于Visio，它不属于专业增强版，所以目前应该无法激活。

**Comment by jm33-m0** [comment]
> 能否添加零售版到批量版的转换

这一点请参考 https://github.com/jm33-m0/kms-activate#office-deployment-tool
这个链接是微软的Office批量部署工具

**Comment by jm33-m0** [comment]
经过测试，通过[Office Deployment Tool](https://www.microsoft.com/en-us/download/details.aspx?id=49117)安装的Office 2019 Enterprise版本（含有Visio Pro 2019）可以被当前版本的kms-activate激活

As I tested, Visio Pro 2019, included in Office Enterprise 2019, can be successfully activated by current version of kms-activate. [Office Deployment Tool](https://www.microsoft.com/en-us/download/details.aspx?id=49117)

[如何使用Office Deployment Tool (How to use Office Deployment Tool)](https://github.com/jm33-m0/kms-activate#office-deployment-tool)

![image](https://user-images.githubusercontent.com/10167884/77246430-27e2ef00-6c62-11ea-8b49-fa536d90a35f.png)

**Comment by jm33-m0** [comment]
> 能否添加零售版到批量版的转换

零售版到批量版可以转换，有脚本可用：https://gist.github.com/roldaojr/8f8cebaa44c6ac34d2f08df2145083c7
