### ISSUE TITLE
V1.3激活直接退出

### ISSUE THREAD

**Issue by moonyuxr** [jm33-m0/kms-activate#8]
使用office_deploy中的install-office.bat下载安装office，打开kms-activate，选择office，点击激活，软件迅速提示kms-activate已停止工作。尝试多次未果，下载V1.2版本后可以正常激活

**Comment by jm33-m0** [comment]
是的，1.3版本属于测试版，这个问题是已知的。
如果你仅需要激活Vol版的office（就像你所说的），那么使用稳定版可以满足需求。
另外office install的脚本可以单独下载。

**Comment by jm33-m0** [comment]
可以尝试[1.3.1](https://github.com/jm33-m0/kms-activate/releases/tag/v1.3.1)，我测试没有崩溃问题。
issue暂时关闭了。
